livraison_index:
    path:     /
    defaults: { _controller: "BikeBundle:Livraison:index" }
    methods:  GET

livraison_show:
    path:     /{id}/show
    defaults: { _controller: "BikeBundle:Livraison:show" }
    methods:  GET

livraison_map:
    path:     /map
    defaults: { _controller: "BikeBundle:Livraison:map" }

livraison_new:
    path:     /new
    defaults: { _controller: "BikeBundle:Livraison:new" }
    methods:  [GET, POST]

livraison_edit:
    path:     /{id}/edit
    defaults: { _controller: "BikeBundle:Livraison:edit" }
    methods:  [GET, POST]

livraison_delete:
    path:     /{id}/delete
    defaults: { _controller: "BikeBundle:Livraison:delete" }
    methods:  DELETE



livraison_ville:
    path:     /map/{ville}
    defaults: { _controller: "BikeBundle:Livraison:ville" }



livraison_pdf:
    path:     /pdf
    defaults: { _controller: "BikeBundle:Livraison:pdf" }

livraison_imp:
    path:     /imp
    defaults: { _controller: "BikeBundle:Livraison:imp" }